name: Generate Snake

on:
  schedule: # Ejecuta una vez al día a medianoche
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/snake.svg

      - name: Create output folder
        run: mkdir -p output

      - name: Move Snake Animation to output folder
        run: mv dist/snake.svg output/snake.svg

      - name: Upload the animation
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: output/snake.svg
